spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/screen?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: ZmQ4444qq

  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
server:
  port: 9090
  servlet:
    context-path: /back

erupt:
  upload-path: E:\Java idea\demo\src\main\resources\static\avatar
  keep-upload-file-name: true
